app:
  name: Case Tracker
  slug: case-tracker
  version: 0.1.0
  description: Simple exception/case tracker demo for Project Abay.
runtime:
  type: supabase
  tenancy:
    model: shared-db
    tenantIdField: tenant_id
security:
  auth:
    provider: supabase
  rbac:
    roles:
      - admin
      - analyst
      - viewer
data:
  entities:
    - name: Case
      table: cases
      fields:
        - { name: id, type: uuid, primaryKey: true, default: gen_random_uuid }
        - { name: tenant_id, type: text, required: true, indexed: true }
        - { name: title, type: text, required: true }
        - { name: status, type: enum, enum: [New, InReview, Resolved], required: true, default: New }
        - { name: created_at, type: timestamptz, required: true, default: now }
    - name: Comment
      table: comments
      fields:
        - { name: id, type: uuid, primaryKey: true, default: gen_random_uuid }
        - { name: tenant_id, type: text, required: true, indexed: true }
        - { name: case_id, type: uuid, required: true, indexed: true, references: { table: cases, field: id } }
        - { name: body, type: text, required: true }
        - { name: created_at, type: timestamptz, required: true, default: now }
ui:
  pages:
    - type: list
      entity: Case
      path: /cases
    - type: detail
      entity: Case
      path: /cases/:id
    - type: list
      entity: Comment
      path: /comments
workflows:
  - name: CaseLifecycle
    entity: Case
    stateField: status
    states: [New, InReview, Resolved]
    transitions:
      - { from: New, to: InReview, roles: [admin, analyst] }
      - { from: InReview, to: Resolved, roles: [admin, analyst] }
audit:
  enabled: true
  events: [create, update, delete, workflow_transition]
