app:
  name: My Abay App
  slug: my-abay-app
  version: 0.1.0
  description: ''
runtime:
  type: supabase
  tenancy:
    model: shared-db
    tenantIdField: tenant_id
security:
  auth:
    provider: supabase
  rbac:
    roles:
      - admin
      - user
data:
  entities: []
ui:
  pages: []
workflows: []
audit:
  enabled: true
  events:
    - create
    - update
    - delete
